language: minimal

services:
  - docker

env:
  global:
    - SCHFILE=wiring.sch
    - PDFFILE=wiring-$TRAVIS_TAG-$TRAVIS_COMMIT.pdf

jobs:
  include:
    - stage: GitHub Release
      script:
        - mkdir output
        - chmod 777 output
        - docker run --rm -t -v $(readlink -f .):/project:ro -v $(readlink -f .)/output:/output:rw -w=/project danielkucera/eeshow 
          eeplot -o /output/$PDFFILE $SCHFILE *.lib
      
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        file_glob: true
        file:
          - output/*
#        on:
#          tags: true
